wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692559416.969027
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      3:
      - 2
      - 17
      - 19
      - 23
      - 37
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 5
      - 12
num_epochs:
  desc: null
  value: 15
criterion_label_classifier:
  desc: null
  value: CrossEntropyLoss()
criterion_known_unknown_classifier:
  desc: null
  value: BCEWithLogitsLoss()
device:
  desc: null
  value: cpu
batch_size:
  desc: null
  value: 8
dataset_choice:
  desc: null
  value: Giacomo
subset_flag:
  desc: null
  value: false
obs_num:
  desc: null
  value: 30
num_classes_to_remove:
  desc: null
  value: 2
g_open_set:
  desc: null
  value: true
hard_reset:
  desc: null
  value: false
class_validation:
  desc: null
  value: false
adaptation_direction:
  desc: null
  value: hmdb2ucf
baseline_or_proposed:
  desc: null
  value: proposed
optimizer_label:
  desc: null
  value: "SGD (\nParameter Group 0\n    dampening: 0\n    differentiable: False\n\
    \    foreach: None\n    lr: 0.001\n    maximize: False\n    momentum: 0.9\n  \
    \  nesterov: False\n    weight_decay: 0\n)"
optimizer_known_unknown:
  desc: null
  value: "SGD (\nParameter Group 0\n    dampening: 0\n    differentiable: False\n\
    \    foreach: None\n    lr: 0.001\n    maximize: False\n    momentum: 0.9\n  \
    \  nesterov: False\n    weight_decay: 0\n)"
