wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700044657.063241
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 15
      - 17
      - 19
      - 23
      - 37
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
num_epochs:
  desc: null
  value: 15
device:
  desc: null
  value: cuda
batch_size:
  desc: null
  value: 8
dataset_choice:
  desc: null
  value: Giacomo
subset_flag:
  desc: null
  value: false
obs_num:
  desc: null
  value: 30
num_classes_to_remove:
  desc: null
  value: 2
g_open_set:
  desc: null
  value: false
hard_reset:
  desc: null
  value: false
class_validation:
  desc: null
  value: false
adaptation_direction:
  desc: null
  value: hmdb2ucf
baseline_or_proposed:
  desc: null
  value: proposed
criterion_label_classifier:
  desc: null
  value: CrossEntropyLoss()
criterion:
  desc: null
  value: CrossEntropyLoss()
log_dir:
  desc: null
  value: ./logs/source_target
seed:
  desc: null
  value: 42
reduction:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.5
n_layers:
  desc: null
  value: 3
source_train_txt:
  desc: null
  value: /content/openset_domain_adaptation/paths/hmdb_train.txt
source_test_txt:
  desc: null
  value: /content/openset_domain_adaptation/paths/hmdb_test.txt
target_train_txt:
  desc: null
  value: /content/openset_domain_adaptation/paths/ucf_train.txt
target_test_txt:
  desc: null
  value: /content/openset_domain_adaptation/paths/ucf_test.txt
path_source_train:
  desc: null
  value: /content/openset_domain_adaptation/hmdb_ucf/hmdb/train
path_source_test:
  desc: null
  value: /content/openset_domain_adaptation/hmdb_ucf/hmdb/test
path_target_train:
  desc: null
  value: /content/openset_domain_adaptation/hmdb_ucf/ucf/train
path_target_test:
  desc: null
  value: /content/openset_domain_adaptation/hmdb_ucf/ucf/test
model_dir:
  desc: null
  value: /content/drive/MyDrive/datasets-thesis/model
n_frames:
  desc: null
  value: 22
strategy:
  desc: null
  value: random
train_classes:
  desc: null
  value:
    golf: '2'
    shoot_ball: '9'
    ride_bike: '7'
    walk: '11'
    kick_ball: '3'
    climb: '0'
    shoot_bow: '10'
    pushup: '6'
    punch: '5'
    fencing: '1'
    ride_horse: '8'
    pullup: '4'
test_classes:
  desc: null
  value:
    golf: '2'
    shoot_ball: '9'
    ride_bike: '7'
    walk: '11'
    kick_ball: '3'
    climb: '0'
    shoot_bow: '10'
    pushup: '6'
    punch: '5'
    fencing: '1'
    ride_horse: '8'
    pullup: '4'
num_classes:
  desc: null
  value: 12
model:
  desc: null
  value: "CEVTModel(\n  (feature_extractor): Sequential(\n    (0): Conv2d(3, 64, kernel_size=(7,\
    \ 7), stride=(2, 2), padding=(3, 3), bias=False)\n    (1): BatchNorm2d(64, eps=1e-05,\
    \ momentum=0.1, affine=True, track_running_stats=True)\n    (2): ReLU(inplace=True)\n\
    \    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)\n\
    \    (4): Sequential(\n      (0): BasicBlock(\n        (conv1): Conv2d(64, 64,\
    \ kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n        (bn1):\
    \ BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \        (relu): ReLU(inplace=True)\n        (conv2): Conv2d(64, 64, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n        (bn2): BatchNorm2d(64,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n      )\n \
    \     (1): BasicBlock(\n        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1,\
    \ 1), padding=(1, 1), bias=False)\n        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n        (relu): ReLU(inplace=True)\n\
    \        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1,\
    \ 1), bias=False)\n        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n      )\n    )\n    (5): Sequential(\n      (0):\
    \ BasicBlock(\n        (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2,\
    \ 2), padding=(1, 1), bias=False)\n        (bn1): BatchNorm2d(128, eps=1e-05,\
    \ momentum=0.1, affine=True, track_running_stats=True)\n        (relu): ReLU(inplace=True)\n\
    \        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1,\
    \ 1), bias=False)\n        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n        (downsample): Sequential(\n          (0):\
    \ Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)\n          (1):\
    \ BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \        )\n      )\n      (1): BasicBlock(\n        (conv1): Conv2d(128, 128,\
    \ kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n        (bn1):\
    \ BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \        (relu): ReLU(inplace=True)\n        (conv2): Conv2d(128, 128, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n        (bn2): BatchNorm2d(128,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n      )\n \
    \   )\n    (6): Sequential(\n      (0): BasicBlock(\n        (conv1): Conv2d(128,\
    \ 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n      \
    \  (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \        (relu): ReLU(inplace=True)\n        (conv2): Conv2d(256, 256, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n        (bn2): BatchNorm2d(256,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n        (downsample):\
    \ Sequential(\n          (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2,\
    \ 2), bias=False)\n          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n        )\n      )\n      (1): BasicBlock(\n    \
    \    (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1,\
    \ 1), bias=False)\n        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n        (relu): ReLU(inplace=True)\n        (conv2):\
    \ Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n\
    \        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      )\n    )\n    (7): Sequential(\n      (0): BasicBlock(\n        (conv1):\
    \ Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n\
    \        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \        (relu): ReLU(inplace=True)\n        (conv2): Conv2d(512, 512, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n        (bn2): BatchNorm2d(512,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n        (downsample):\
    \ Sequential(\n          (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2,\
    \ 2), bias=False)\n          (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n        )\n      )\n      (1): BasicBlock(\n    \
    \    (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1,\
    \ 1), bias=False)\n        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n        (relu): ReLU(inplace=True)\n        (conv2):\
    \ Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n\
    \        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      )\n    )\n    (8): AdaptiveAvgPool2d(output_size=(1, 1))\n  )\n  (classifier):\
    \ Linear(in_features=512, out_features=12, bias=True)\n)"
optimizer:
  desc: null
  value: "SGD (\nParameter Group 0\n    dampening: 0\n    differentiable: False\n\
    \    foreach: None\n    lr: 0.001\n    maximize: False\n    momentum: 0.9\n  \
    \  nesterov: False\n    weight_decay: 0\n)"
train-result-hmdb2ucf:
  desc: null
  value:
    random-22:
      epoch_15:
        avg_acc: 0.9948453608247423
        acc_by_class:
        - 1.0
        - 0.9636363636363636
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 0.9710144927536232
        - 1.0
        - 1.0
        - 1.0
        - 1.0
test-result-hmdb2ucf:
  desc: null
  value:
    random-22:
      epoch_15:
        avg_acc: 0.857566765578635
        acc_by_class:
        - 0.7916666666666666
        - 0.96
        - 0.9
        - 0.7272727272727273
        - 1.0
        - 0.4
        - 1.0
        - 1.0
        - 0.8620689655172413
        - 0.9
        - 0.9333333333333333
        - 0.8
