wandb_version: 1

entropy:
  desc: null
  value: 0.05
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687697714.681087
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 17
      - 23
      - 37
      4: 3.10.12
      5: 0.15.4
      8:
      - 1
      - 5
      - 12
